### ISSUE TITLE
Allow breakpoint of [0,0]

### ISSUE THREAD

**Issue by mboynes** [alleyinteractive/ad-layers#46]
[DFP's docs on building responsive ads](https://support.google.com/dfp_premium/answer/3423562?hl=en) says:

> A browser size mapping of [0, 0] can be used to specify a default mapping that can be used on any browser size.

Setting a width and height of 0 doesn't work in Ad Layers. You can set it to be `[1,1]` which works just as well, but `[0,0]` should be supported.

The underlying bug is upstream in alleyinteractive/wordpress-fieldmanager#493.

**Comment by Souvent22** [comment]
I created a PR for this issue:

https://github.com/alleyinteractive/ad-layers/pull/47

**Comment by mboynes** [comment]
Fixed in alleyinteractive/wordpress-fieldmanager#500.
