### ISSUE TITLE
Is this plugin still being maintained?

### ISSUE THREAD

**Issue by anekola** [alleyinteractive/ad-layers#89]
It's still working and in use on our sites, but I'm concerned about relying on it in the future. Can someone at the Alley team provide thoughts?

**Comment by mboynes** [comment]
Hi @anekola, it is still being maintained! Right now, we're mainly just shipping bug fixes, but we're kicking around ideas for large changes as well (e.g. cool things we could do with Gutenberg, how we might automate slot setups using Google's API, stuff like that). If you have anything on your wishlist, please share it in an issue!
